"""add review_requests table

Revision ID: 035cae603030
Revises: 78ecb7960ad6
Create Date: 2026-08-29 17:51:50.884100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '035cae603030'
down_revision: Union[str, None] = '78ecb7960ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    # `conversationchannel` already exists as a Postgres enum type (created by
    # the original `conversations` table migration) — create_type=False avoids
    # a DuplicateObjectError trying to recreate it. See c671868ced69's comment
    # for the same gotcha with generic sa.Enum in this SQLAlchemy version.
    sa.Column('channel', postgresql.ENUM('PHONE', 'SMS', 'WHATSAPP', 'INSTAGRAM', 'FACEBOOK', 'WEB_CHAT', 'EMAIL', name='conversationchannel', create_type=False), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('review_link_clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_requests')
    # ### end Alembic commands ###
