"""pending signup claim fields

Revision ID: 0f7e95e96fe1
Revises: 0355cb292dd8
Create Date: 2026-08-25 15:05:13.439028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7e95e96fe1'
down_revision: Union[str, None] = '0355cb292dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_signups', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pending_signups', sa.Column('claimed_by_clerk_id', sa.String(length=255), nullable=True))
    op.add_column('pending_signups', sa.Column('practice_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'pending_signups', 'practices', ['practice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pending_signups', type_='foreignkey')
    op.drop_column('pending_signups', 'practice_id')
    op.drop_column('pending_signups', 'claimed_by_clerk_id')
    op.drop_column('pending_signups', 'claimed_at')
    # ### end Alembic commands ###
