"""patient doctor assignment, archive, consent discussed

Revision ID: 4e24e74ecd6a
Revises: e6139e68c067
Create Date: 2026-09-07 15:49:33.108255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e24e74ecd6a'
down_revision: Union[str, None] = 'e6139e68c067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consent_documents', sa.Column('discussed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('consent_documents', sa.Column('discussed_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'consent_documents', 'users', ['discussed_by'], ['id'])
    op.add_column('patients', sa.Column('assigned_doctor_id', sa.UUID(), nullable=True))
    op.add_column('patients', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('patients', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('patients', sa.Column('archived_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'patients', 'doctors', ['assigned_doctor_id'], ['id'])
    op.create_foreign_key(None, 'patients', 'users', ['archived_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'archived_by')
    op.drop_column('patients', 'archived_at')
    op.drop_column('patients', 'is_archived')
    op.drop_column('patients', 'assigned_doctor_id')
    op.drop_constraint(None, 'consent_documents', type_='foreignkey')
    op.drop_column('consent_documents', 'discussed_by')
    op.drop_column('consent_documents', 'discussed_at')
    # ### end Alembic commands ###
