"""add patient qualification and intake_summary fields

Revision ID: 637981c7f7dc
Revises: 9f23fd95a137
Create Date: 2026-09-06 12:12:29.421367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '637981c7f7dc'
down_revision: Union[str, None] = '9f23fd95a137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('qualification', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('patients', sa.Column('intake_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'intake_summary')
    op.drop_column('patients', 'qualification')
    # ### end Alembic commands ###
