"""patient_portal_id_pin_auth

Revision ID: 785aeb9feeef
Revises: e9383b8b9f78
Create Date: 2026-09-02 16:13:27.758285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785aeb9feeef'
down_revision: Union[str, None] = 'e9383b8b9f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('portal_id', sa.String(length=32), nullable=True))
    op.add_column('patients', sa.Column('portal_pin_hash', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('uq_patients_portal_token'), 'patients', type_='unique')
    op.create_unique_constraint(None, 'patients', ['portal_id'])
    op.drop_column('patients', 'portal_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('portal_token', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'patients', type_='unique')
    op.create_unique_constraint(op.f('uq_patients_portal_token'), 'patients', ['portal_token'], postgresql_nulls_not_distinct=False)
    op.drop_column('patients', 'portal_pin_hash')
    op.drop_column('patients', 'portal_id')
    # ### end Alembic commands ###
