"""add unique constraint on agent_configs practice_id agent_type

Revision ID: 78ecb7960ad6
Revises: ce26d0081fb6
Create Date: 2026-08-29 17:15:00.026028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78ecb7960ad6'
down_revision: Union[str, None] = 'ce26d0081fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_agent_config_practice_agent', 'agent_configs', ['practice_id', 'agent_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_agent_config_practice_agent', 'agent_configs', type_='unique')
    # ### end Alembic commands ###
