"""leads_funnel_and_inventory

Revision ID: 8cd4239466e2
Revises: 449b6bea9a5b
Create Date: 2026-08-31 13:26:50.572972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8cd4239466e2'
down_revision: Union[str, None] = '449b6bea9a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('reorder_threshold', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('received_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # A brand-new enum type used via op.add_column (not op.create_table)
    # needs its CREATE TYPE issued explicitly — SQLAlchemy's automatic
    # create-on-table-create hook doesn't fire for ALTER TABLE ADD COLUMN.
    # create_type=False on the column itself then avoids a second, redundant
    # attempt (which would fail with "type already exists").
    lifecycle_stage_enum = postgresql.ENUM(
        'INQUIRY', 'CONTACTED', 'CONSULT_SCHEDULED', 'CONSULT_COMPLETED', 'TREATMENT_PLANNED', 'PATIENT', 'LOST',
        name='patientlifecyclestage',
    )
    lifecycle_stage_enum.create(op.get_bind(), checkfirst=True)
    # server_default backfills the 2 existing patient rows to a sane
    # starting stage — dropped right after so future inserts rely on the
    # model's own Python-side default instead of a DB-level one.
    op.add_column(
        'patients',
        sa.Column(
            'lifecycle_stage',
            postgresql.ENUM(
                'INQUIRY', 'CONTACTED', 'CONSULT_SCHEDULED', 'CONSULT_COMPLETED', 'TREATMENT_PLANNED', 'PATIENT', 'LOST',
                name='patientlifecyclestage', create_type=False,
            ),
            nullable=False,
            server_default='INQUIRY',
        ),
    )
    op.alter_column('patients', 'lifecycle_stage', server_default=None)
    op.add_column('patients', sa.Column('lost_reason', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'source')
    op.drop_column('patients', 'lost_reason')
    op.drop_column('patients', 'lifecycle_stage')
    postgresql.ENUM(name='patientlifecyclestage').drop(op.get_bind(), checkfirst=True)
    op.drop_table('inventory_batches')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
