"""front_desk_status_and_waitlist

Revision ID: a2d1b15d44a7
Revises: 785aeb9feeef
Create Date: 2026-09-03 18:08:02.599894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d1b15d44a7'
down_revision: Union[str, None] = '785aeb9feeef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Autogenerate doesn't detect new labels on an existing PG enum type —
    # same gotcha this project has hit before. SQLAlchemy's Enum(...) column
    # stores the Python member NAME (confirmed against the live DB: e.g.
    # 'COMPLETED', not 'completed'), so the new labels must match that
    # casing, not AppointmentStatus's lowercase .value.
    op.execute("ALTER TYPE appointmentstatus ADD VALUE IF NOT EXISTS 'WITH_DOCTOR'")
    op.execute("ALTER TYPE appointmentstatus ADD VALUE IF NOT EXISTS 'READY_FOR_CHECKOUT'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('requested_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('WAITING', 'FULFILLED', 'CANCELLED', name='waitlistentrystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('appointments', sa.Column('with_doctor_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointments', sa.Column('ready_for_checkout_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'ready_for_checkout_at')
    op.drop_column('appointments', 'with_doctor_at')
    op.drop_table('waitlist_entries')
    # ### end Alembic commands ###
    # Postgres has no ALTER TYPE ... DROP VALUE — removing the two new enum
    # labels would require recreating the whole type. Left in place on
    # downgrade; harmless since nothing downstream requires their absence.
