"""add recovery_checkins table

Revision ID: a420e813d556
Revises: f44c25bdbd98
Create Date: 2026-09-05 21:02:49.038150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a420e813d556'
down_revision: Union[str, None] = 'f44c25bdbd98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_checkins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recovery_journal_id', sa.UUID(), nullable=False),
    sa.Column('checkpoint', sa.Enum('DAY_1', 'DAY_3', 'DAY_7', 'DAY_14', 'MONTH_1', 'OTHER', name='recoverycheckpoint'), nullable=False),
    sa.Column('pain_score', sa.Integer(), nullable=True),
    sa.Column('swelling_level', sa.Enum('NONE', 'MILD', 'MODERATE', 'SEVERE', name='swellinglevel'), nullable=True),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('concerns', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('flagged_for_review', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.String(length=255), nullable=True),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recovery_journal_id'], ['recovery_journals.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recovery_checkins')
    # ### end Alembic commands ###
