"""invoice_redesign_and_line_items

Revision ID: ad596b1f52ec
Revises: 8d3eadc0e541
Create Date: 2026-08-30 22:37:18.064324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad596b1f52ec'
down_revision: Union[str, None] = '8d3eadc0e541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('treatment_plan_item_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['treatment_plan_item_id'], ['treatment_plan_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('invoices', sa.Column('treatment_plan_id', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('subtotal_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.create_foreign_key(None, 'invoices', 'treatment_plans', ['treatment_plan_id'], ['id'])
    op.drop_column('invoices', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'total_amount')
    op.drop_column('invoices', 'discount_amount')
    op.drop_column('invoices', 'tax_amount')
    op.drop_column('invoices', 'subtotal_amount')
    op.drop_column('invoices', 'treatment_plan_id')
    op.drop_table('invoice_line_items')
    # ### end Alembic commands ###
