"""week2_patient_depth_consent_versioning_photo_timeline_surgery

Revision ID: adf80d56f06e
Revises: a2d1b15d44a7
Create Date: 2026-09-04 18:21:05.466961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adf80d56f06e'
down_revision: Union[str, None] = 'a2d1b15d44a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surgeries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('procedure_id', sa.UUID(), nullable=True),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('assistant_doctor_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_appointment_id', sa.UUID(), nullable=True),
    sa.Column('recovery_journal_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_estimate_minutes', sa.Integer(), nullable=True),
    sa.Column('anesthesia_type', sa.String(length=100), nullable=True),
    sa.Column('facility_note', sa.Text(), nullable=True),
    sa.Column('pre_op_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('implants_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('operative_note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'COMPLETED', 'CANCELLED', name='surgerystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assistant_doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.ForeignKeyConstraint(['recovery_journal_id'], ['recovery_journals.id'], ),
    sa.ForeignKeyConstraint(['scheduled_appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('consent_documents', sa.Column('template_id', sa.UUID(), nullable=True))
    op.add_column('consent_documents', sa.Column('template_version', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'consent_documents', 'consent_templates', ['template_id'], ['id'])
    op.add_column('patient_photos', sa.Column('stage', sa.String(length=20), nullable=True))
    op.add_column('patient_photos', sa.Column('body_area', sa.String(length=100), nullable=True))
    op.add_column('patient_photos', sa.Column('procedure_id', sa.UUID(), nullable=True))
    op.add_column('patient_photos', sa.Column('is_marketing_approved', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_foreign_key(None, 'patient_photos', 'procedures', ['procedure_id'], ['id'])
    op.add_column('patients', sa.Column('gender', sa.String(length=30), nullable=True))
    op.add_column('patients', sa.Column('emergency_contact_name', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('patients', sa.Column('surgical_history', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('patients', sa.Column('current_medications', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('patients', sa.Column('smoking_status', sa.String(length=30), nullable=True))
    op.add_column('patients', sa.Column('previous_cosmetic_procedures', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('patients', sa.Column('referral_source', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('preferred_language', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('communication_preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('patients', sa.Column('insurance_provider', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('insurance_number', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'insurance_number')
    op.drop_column('patients', 'insurance_provider')
    op.drop_column('patients', 'communication_preferences')
    op.drop_column('patients', 'preferred_language')
    op.drop_column('patients', 'referral_source')
    op.drop_column('patients', 'previous_cosmetic_procedures')
    op.drop_column('patients', 'smoking_status')
    op.drop_column('patients', 'current_medications')
    op.drop_column('patients', 'surgical_history')
    op.drop_column('patients', 'allergies')
    op.drop_column('patients', 'emergency_contact_phone')
    op.drop_column('patients', 'emergency_contact_name')
    op.drop_column('patients', 'gender')
    op.drop_constraint(None, 'patient_photos', type_='foreignkey')
    op.drop_column('patient_photos', 'is_marketing_approved')
    op.drop_column('patient_photos', 'procedure_id')
    op.drop_column('patient_photos', 'body_area')
    op.drop_column('patient_photos', 'stage')
    op.drop_constraint(None, 'consent_documents', type_='foreignkey')
    op.drop_column('consent_documents', 'template_version')
    op.drop_column('consent_documents', 'template_id')
    op.drop_table('surgeries')
    op.drop_table('consent_templates')
    # ### end Alembic commands ###
