"""platform admin and plans

Revision ID: c9da7a5261a3
Revises: d88cd21b7c1f
Create Date: 2026-08-28 17:01:05.796390

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9da7a5261a3'
down_revision: Union[str, None] = 'd88cd21b7c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# NOTE: autogenerate also detected a pre-existing 'uq_agent_config_practice_agent'
# constraint drift on agent_configs (model has it, DB didn't) — deliberately
# left OUT of this migration since it's unrelated to platform-admin/plans and
# risks failing if duplicate (practice_id, agent_type) rows already exist.
# Flagged here rather than silently bundled in; a separate migration should
# add it after checking for dupes.


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # create_type=False — the 'subscriptiontier' enum type already exists
    # (created by the initial_schema migration for subscriptions.tier);
    # reusing it here by name would otherwise re-issue CREATE TYPE and fail.
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tier', postgresql.ENUM('SOLO', 'PRACTICE', 'ENTERPRISE', 'CUSTOM', name='subscriptiontier', create_type=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('billing_period', sa.String(length=20), nullable=False),
    sa.Column('is_custom_pricing', sa.Boolean(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_doctors', sa.Integer(), nullable=True),
    sa.Column('max_social_channels', sa.Integer(), nullable=True),
    sa.Column('max_locations', sa.Integer(), nullable=True),
    sa.Column('has_analytics', sa.Boolean(), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('highlight', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier')
    )
    op.add_column('users', sa.Column('is_platform_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###

    # Seed the 3 real plans (mirrors frontend/src/data/plans.ts +
    # services/practice/plan_capabilities.py) so a fresh DB is never planless
    # — same self-seeding philosophy as AgentCosting, done here at migration
    # time since Plan is admin-owned reference data, not lazily created on
    # first unauthenticated read.
    plans_table = sa.table(
        'plans',
        sa.column('id', sa.UUID()),
        sa.column('tier', postgresql.ENUM('SOLO', 'PRACTICE', 'ENTERPRISE', 'CUSTOM', name='subscriptiontier', create_type=False)),
        sa.column('name', sa.String()),
        sa.column('tagline', sa.String()),
        sa.column('price', sa.Numeric()),
        sa.column('billing_period', sa.String()),
        sa.column('is_custom_pricing', sa.Boolean()),
        sa.column('features', postgresql.JSONB()),
        sa.column('agent_categories', postgresql.JSONB()),
        sa.column('max_doctors', sa.Integer()),
        sa.column('max_social_channels', sa.Integer()),
        sa.column('max_locations', sa.Integer()),
        sa.column('has_analytics', sa.Boolean()),
        sa.column('is_active', sa.Boolean()),
        sa.column('highlight', sa.Boolean()),
        sa.column('display_order', sa.Integer()),
    )
    op.bulk_insert(plans_table, [
        {
            'id': uuid.uuid4(), 'tier': 'SOLO', 'name': 'Solo',
            'tagline': 'For single-surgeon practices', 'price': 690, 'billing_period': 'monthly',
            'is_custom_pricing': False,
            'features': [
                'Front desk & intake agents', 'Booking, reminders & rescheduling',
                '1 connected social channel', 'Multilingual support', 'Email support',
            ],
            'agent_categories': ['front-desk'],
            'max_doctors': 1, 'max_social_channels': 1, 'max_locations': 1,
            'has_analytics': False, 'is_active': True, 'highlight': False, 'display_order': 0,
        },
        {
            'id': uuid.uuid4(), 'tier': 'PRACTICE', 'name': 'Practice',
            'tagline': 'For growing multi-surgeon clinics', 'price': 1690, 'billing_period': 'monthly',
            'is_custom_pricing': False,
            'features': [
                'Everything in Solo', 'Full consultation & surgery agents',
                'Post-surgery care & recovery suite', 'All social channels connected',
                'Analytics dashboard', 'Priority onboarding & support',
            ],
            'agent_categories': ['front-desk', 'consultation', 'surgery', 'post-care'],
            'max_doctors': None, 'max_social_channels': None, 'max_locations': 1,
            'has_analytics': True, 'is_active': True, 'highlight': True, 'display_order': 1,
        },
        {
            'id': uuid.uuid4(), 'tier': 'ENTERPRISE', 'name': 'Enterprise',
            'tagline': 'For groups & multi-location brands', 'price': None, 'billing_period': 'monthly',
            'is_custom_pricing': True,
            'features': [
                'Everything in Practice', 'All 31 agents, fully configured',
                'Multi-location orchestration', 'Custom integrations & EHR',
                'BAA & dedicated success manager',
            ],
            'agent_categories': ['front-desk', 'consultation', 'surgery', 'post-care', 'business'],
            'max_doctors': None, 'max_social_channels': None, 'max_locations': None,
            'has_analytics': True, 'is_active': True, 'highlight': False, 'display_order': 2,
        },
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_platform_admin')
    op.drop_table('plans')
    # ### end Alembic commands ###
