"""agent costing and patient AI assignment fields

Revision ID: d88cd21b7c1f
Revises: 0f7e95e96fe1
Create Date: 2026-08-25 18:49:06.497624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd88cd21b7c1f'
down_revision: Union[str, None] = '0f7e95e96fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_costing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_slug', sa.String(length=50), nullable=False),
    sa.Column('cost_per_session', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('total_earned', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_slug')
    )
    op.add_column('patients', sa.Column('plan_type', sa.String(length=50), nullable=False))
    op.add_column('patients', sa.Column('chief_complaint', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('needs_surgery', sa.Boolean(), nullable=False))
    op.add_column('patients', sa.Column('ai_agent_assigned', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('agent_status', sa.String(length=20), nullable=False))
    op.add_column('patients', sa.Column('agent_cost', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'agent_cost')
    op.drop_column('patients', 'agent_status')
    op.drop_column('patients', 'ai_agent_assigned')
    op.drop_column('patients', 'needs_surgery')
    op.drop_column('patients', 'chief_complaint')
    op.drop_column('patients', 'plan_type')
    op.drop_table('agent_costing')
    # ### end Alembic commands ###
