"""drop patient portal_pin_hash, retire PIN login

Revision ID: e6139e68c067
Revises: 9c41f7d2ab10
Create Date: 2026-09-07 14:43:20.781026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6139e68c067'
down_revision: Union[str, None] = '9c41f7d2ab10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'portal_pin_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('portal_pin_hash', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
