"""doctor_enrichment_procedures_availability

Revision ID: e9383b8b9f78
Revises: b7c8d9e0f1a3
Create Date: 2026-09-02 16:06:42.175117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9383b8b9f78'
down_revision: Union[str, None] = 'b7c8d9e0f1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_procedures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('procedure_id', sa.UUID(), nullable=False),
    sa.Column('consultation_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('surgery_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default backfills the practice's existing doctor rows — the
    # model's own Python-side default=list/dict only applies to future
    # ORM-created rows, not columns being added to an already-populated table.
    op.add_column('doctors', sa.Column('qualifications', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('doctors', sa.Column('specializations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('doctors', sa.Column('working_hours', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('doctors', sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('doctors', sa.Column('signature_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'signature_url')
    op.drop_column('doctors', 'commission_percent')
    op.drop_column('doctors', 'working_hours')
    op.drop_column('doctors', 'specializations')
    op.drop_column('doctors', 'qualifications')
    op.drop_table('doctor_procedures')
    op.drop_table('doctor_availability')
    # ### end Alembic commands ###
